export const asseets=[
 
    { url: "./explota/0.png", name: "explota0" },
    { url: "./explota/1.png", name: "explota1" },
    { url: "./explota/2.png", name: "explota2" },
    { url: "./explota/3.png", name: "explota3" },
    { url: "./explota/4.png", name: "explota4" },
    { url: "./explota/5.png", name: "explota5" },
    { url: "./explota/6.png", name: "explota6" },
    { url: "./explota/7.png", name: "explota7" },
    { url: "./explota/8.png", name: "explota8" },
    { url: "./explota/9.png", name: "explota9" },
    { url: "./explota/10.png", name: "explota10" },
    { url: "./explota/11.png", name: "explota11" },
    { url: "./explota/12.png", name: "explota12" },
    { url: "./explota/13.png", name: "explota13" },
    { url: "./explota/14.png", name: "explota14" },
    { url: "./explota/15.png", name: "explota15" },
    
    { url: "./asteroidegris/a10000.png", name: "asteroideg0" },
    { url: "./asteroidegris/a10001.png", name: "asteroideg1" },
    { url: "./asteroidegris/a10002.png", name: "asteroideg2" },
    { url: "./asteroidegris/a10003.png", name: "asteroideg3" },
    { url: "./asteroidegris/a10004.png", name: "asteroideg4" },
    { url: "./asteroidegris/a10005.png", name: "asteroideg5" },
    { url: "./asteroidegris/a10006.png", name: "asteroideg6" },
    { url: "./asteroidegris/a10007.png", name: "asteroideg7" },
    { url: "./asteroidegris/a10008.png", name: "asteroideg8" },
    { url: "./asteroidegris/a10009.png", name: "asteroideg9" },
    { url: "./asteroidegris/a10010.png", name: "asteroideg10" },
    { url: "./asteroidegris/a10011.png", name: "asteroideg11" },
    { url: "./asteroidegris/a10012.png", name: "asteroideg12" },
    { url: "./asteroidegris/a10013.png", name: "asteroideg13" },
    { url: "./asteroidegris/a10014.png", name: "asteroideg14" },
    { url: "./asteroidegris/a10015.png", name: "asteroideg15" },
    
    { url: "./asteroiderojo/a30000.png", name: "asteroider0" },
    { url: "./asteroiderojo/a30001.png", name: "asteroider1" },
    { url: "./asteroiderojo/a30002.png", name: "asteroider2" },
    { url: "./asteroiderojo/a30003.png", name: "asteroider3" },
    { url: "./asteroiderojo/a30004.png", name: "asteroider4" },
    { url: "./asteroiderojo/a30005.png", name: "asteroider5" },
    { url: "./asteroiderojo/a30006.png", name: "asteroider6" },
    { url: "./asteroiderojo/a30007.png", name: "asteroider7" },
    { url: "./asteroiderojo/a30008.png", name: "asteroider8" },
    { url: "./asteroiderojo/a30009.png", name: "asteroider9" },
    { url: "./asteroiderojo/a30010.png", name: "asteroider10" },
    { url: "./asteroiderojo/a30011.png", name: "asteroider11" },
    { url: "./asteroiderojo/a30012.png", name: "asteroider12" },
    { url: "./asteroiderojo/a30013.png", name: "asteroider13" },
    { url: "./asteroiderojo/a30014.png", name: "asteroider14" },
    { url: "./asteroiderojo/a30015.png", name: "asteroider15" },

    { url: "./naveplayer/nave1.png", name: "player1" },
    { url: "./naveplayer/nave2.png", name: "player2" },

    
    { url: "./navepolicia/nave1.png", name: "poli1" },
    { url: "./navepolicia/nave2.png", name: "poli2" },
    { url: "./navepolicia/nave1.png", name: "poli3" },
    
    {url: "./espacio/Tileable..jpg", name:"Background"},
    {url: "./espacio/block.png", name:"Block"},
    {url: "./espacio/cactus.png", name:"Cactus"},
    {url: "./espacio/platform.png", name:"Platform"},
    
];


